name: cscevsev
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  provider: ^3.1.0
  flutter_spinkit: "^4.0.0"
  google_maps_flutter: ^0.5.25+2
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.0+9
  font_awesome_flutter: ^8.8.1
  cached_network_image: ^2.0.0
  flutter_signin_button: ^0.2.8
  flutter_share_social_media: ^0.2.0
  flutter_share_me: ^0.1.3
  eva_icons_flutter: ^2.0.0
  flutter_launcher_icons: ^0.7.5
  get_it: ^4.0.2
  firebase_storage: ^3.1.5
  json_serializable: ^2.0.2
  path:
  camera:
  geolocator: ^5.3.1
  image_cropper: ^1.2.1
  giffy_dialog: ^1.7.0
  true_time: ^0.1.0
  intl: ^0.16.1
  date_format: ^1.0.8
  flutter_datetime_picker: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_test: ^0.10.3

flutter_icons:
  image_path: "Images/firstLook.png"
  android: "launcher_icon"
  ios: true


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/leaf.png
    - images/leaf2.png
    - images/back1.jpg
    - images/back2.jpg
    - images/original.png
    - images/original2.png
    - images/firstLook.png
    - images/guest1.jpg
    - images/guest2.jpg
    - images/guest3.jpg
    - images/guest4.jpeg
    - images/guest5.jpg
    - images/guest6.jpg
    - images/cop1.jpg
    - images/cop2.jpg
    - images/cop3.jpg
    - images/cop4.jpg
    - images/cop5.jpg
    - images/cop6.jpg
    - images/anonim1.png
    - images/anonim2.png
    - images/nickfrost.jpg
    - images/redMarker.png
    - images/kameraGif.gif
    - images/blueMarker.png
    - images/galleryGif.gif
    - images/emptyGif.gif
    - images/markerGif.gif
    - images/mapMarkerGif.gif
    - images/mapGif.gif
    - images/worldMapGif.gif
    - images/loadGif.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
